### ISSUE TITLE
/getaddr.bitnodes.io:0.1/ peers

### ISSUE THREAD

**Issue by 21E14** [ayeowch/bitnodes#12]
Does it make sense for https://getaddr.bitnodes.io/nodes/ to filer out its own USER_AGENT (/getaddr.bitnodes.io:0.1/)? 'Reachable nodes' have gone undefined, but /getaddr.bitnodes.io:0.1/ is certainly a 'peer' in the reference client sense.

**Comment by ayeowch** [comment]
The crawler is designed to only crawl the network for reachable nodes. It does not listen to incoming connections so it is not considered as a reachable node.

**Comment by 21E14** [comment]
Might be something to look into, as a perspective is lost. I am seeing up to 25% of all inbound peers present the /getaddr.bitnodes.io:0.1/ 'user agent' at times.

**Comment by ayeowch** [comment]
I know there are many 'bitnodes' from Amazon EC2. I don't know who are operating these and I consider them to be extremely abusive towards the network as they are taking up the connection slots from the reachable nodes hence the message in https://github.com/ayeowch/bitnodes#setup.

I am running only 1 instance of the actual crawler from 148.251.238.178; you won't actually see it in your getpeerinfo list since it only connect once to perform handshake then disconnect and repeat the process once a full network snapshot is taken.

**Comment by ayeowch** [comment]
The Amazon EC2 nodes were first seen earlier in December: https://github.com/bitcoin/bitcoin/pull/5545#issuecomment-68173968. They even resulted in some of the devs to think it was me that is operating these nodes since I run getaddr.bitnodes.io and wrote this crawler.
