### ISSUE TITLE
Why does it report my node is down when it is online?

### ISSUE THREAD

**Issue by PegasusNZ** [ayeowch/bitnodes#73]
My node is in hybrid mode on both clearnet and tor! After a reboot it reports correctly for about a day then it says it is down but if I click the link it successfully finds the node on the IP address 210.55.57.179. The node has 39/40 peers

**Comment by ayeowch** [comment]
> After a reboot it reports correctly for about a day then it says it is down

@PegasusNZ Was this for the IPv4 address or .onion?

**Comment by PegasusNZ** [comment]
ip4 address

**Comment by ayeowch** [comment]
@PegasusNZ How is the load looking on the device? I tried 'check node' on your node and got an unreachable response once out of several tries earlier. Might be worth checking if the same issue persist with tor disabled.

**Comment by PegasusNZ** [comment]
> @PegasusNZ How is the load looking on the device? I tried 'check node' on your node and got an unreachable response once out of several tries earlier. Might be worth checking if the same issue persist with tor disabled.

Earlier I was doing some maintenance and installs! Load is very low now?

**Comment by ayeowch** [comment]
I am getting TCP RST packet from your node immediately after my verack message is sent (at the end of handshake). This could be due to firewall along the path or custom Bitcoin node implementation? Try also disabling tor in your Bitcoin node configuration and we could retest IPv4 in isolation.

**Comment by ayeowch** [comment]
@PegasusNZ I am getting TCP RST packet from your node immediately after my verack message is sent (at the end of handshake). This could be due to firewall along the path or custom Bitcoin node implementation? Try also disabling tor in your Bitcoin node configuration and we could retest IPv4 in isolation.

**Comment by ayeowch** [comment]
@PegasusNZ Another potential issue is your system may be hitting its file descriptor limit, similar to the situation found in https://stackoverflow.com/a/5245704. Steps to increase file descriptor limit if you are on Linux system: https://www.cyberciti.biz/faq/linux-increase-the-maximum-number-of-open-files/

**Comment by PegasusNZ** [comment]
Thank you I will try those tips

**Comment by PegasusNZ** [comment]
@ayeowch It was working fine for 10 months, I have not changed any hardware the only change is the Casa 2 node has be reflashed as a RaspiBlitz. I checked the file limits for the user bitcoin it was 256000 system limit is a rather large number over 12 digits! I have disabled tor for bitcoind. I will see in 24 hours if there is any change

**Comment by ayeowch** [comment]
@PegasusNZ Does the reflash to RaspiBlitz date coincide with the recent down spikes (starting around April 30, 2022) in the monthly latency chart in https://bitnodes.io/nodes/210.55.57.179-8333/? Also, were you running in hybrid IPv4 + tor only after the reflash?

**Comment by PegasusNZ** [comment]
Yes this only started happening since I installed RaspiBlitz, On both systems I had TOR enabled, just RaspiBlitz gives more control

**Comment by ayeowch** [comment]
@PegasusNZ Might be worth opening issue with RaspiBlitz to see if there are others experiencing similar issue when having both IPv4 and tor enabled. Since disabling tor, it looks like your node is reachable normally again.
https://bitnodes.io/nodes/210.55.57.179-8333/:
![Screenshot from 2022-05-15 17-57-19](https://user-images.githubusercontent.com/500869/168463078-e45560e7-42ac-4ce4-bf15-124525256d36.png)
